services:
  - type: web
    name: crypto-app
    env: node
    plan: free
    buildCommand: npm install --frozen-lockfile && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
